"""
Pharmacy store locations and configuration.
Edit this file to update store details, printer IPs, etc.
"""

STORES = {
    "102": {
        "name": "Price Chopper Pharmacy",
        "number": "102",
        "address": "1030 West 103rd Street",
        "city": "Kansas City",
        "state": "MO",
        "zip": "64114",
        "phone": "(816) 777-0533",
        "fax": "(816) 777-0535",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",  # Set to Zebra GK420d IP, e.g. "192.168.1.100"
        "printer_port": 9100,
    },
    "104": {
        "name": "Price Chopper Pharmacy",
        "number": "104",
        "address": "1101 S 7 Highway",
        "city": "Blue Springs",
        "state": "MO",
        "zip": "64014",
        "phone": "(816) 229-3252",
        "fax": "(816) 229-1726",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "110": {
        "name": "Price Chopper Pharmacy",
        "number": "110",
        "address": "501 Schug Avenue",
        "city": "Peculiar",
        "state": "MO",
        "zip": "64078",
        "phone": "(816) 758-4047",
        "fax": "(816) 758-5425",
        "hours": {"mon_fri": "9AM-7PM", "sat": "9AM-5PM", "sun": "closed"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "117": {
        "name": "Price Chopper Pharmacy",
        "number": "117",
        "address": "660 East Main Street",
        "city": "Gardner",
        "state": "KS",
        "zip": "66030",
        "phone": "(913) 856-2425",
        "fax": "(913) 856-2187",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "119": {
        "name": "Price Chopper Pharmacy",
        "number": "119",
        "address": "7418 West 119th Street",
        "city": "Overland Park",
        "state": "KS",
        "zip": "66213",
        "phone": "(913) 338-2707",
        "fax": "(913) 338-3606",
        "hours": {"mon_fri": "9AM-7PM", "sat": "9AM-5PM", "sun": "closed"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "121": {
        "name": "Price Chopper Pharmacy",
        "number": "121",
        "address": "3700 West 95th Street",
        "city": "Leawood",
        "state": "KS",
        "zip": "66206",
        "phone": "(913) 648-0133",
        "fax": "(913) 648-0737",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "156": {
        "name": "Sun Fresh Pharmacy",
        "number": "156",
        "address": "10225 N. Oak Trafficway",
        "city": "Kansas City",
        "state": "MO",
        "zip": "64155",
        "phone": "(816) 734-3600",
        "fax": "(816) 734-3606",
        "hours": {"mon_fri": "9AM-7PM", "sat": "9AM-5PM", "sun": "closed"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "157": {
        "name": "Price Chopper Pharmacy",
        "number": "157",
        "address": "937 N.E. Woods Chapel Road",
        "city": "Lee's Summit",
        "state": "MO",
        "zip": "64064",
        "phone": "(816) 246-7300",
        "fax": "(816) 875-1015",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "10.157.4.48",
        "printer_port": 9100,
    },
    "171": {
        "name": "Price Chopper Pharmacy",
        "number": "171",
        "address": "251 S.W. Greenwich Drive",
        "city": "Lee's Summit",
        "state": "MO",
        "zip": "64082",
        "phone": "(816) 744-2104",
        "fax": "(816) 744-2106",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "249": {
        "name": "Price Chopper Pharmacy",
        "number": "249",
        "address": "22210 West 66th Street",
        "city": "Shawnee",
        "state": "KS",
        "zip": "66226",
        "phone": "(913) 422-2134",
        "fax": "(913) 422-2138",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "250": {
        "name": "Price Chopper Pharmacy",
        "number": "250",
        "address": "2101 North 7 Highway",
        "city": "Pleasant Hill",
        "state": "MO",
        "zip": "64080",
        "phone": "(816) 540-3581",
        "fax": "(816) 540-6227",
        "hours": {"mon_fri": "9AM-7PM", "sat": "9AM-5PM", "sun": "closed"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "285": {
        "name": "Price Chopper Pharmacy",
        "number": "285",
        "address": "900 West Foxwood Drive",
        "city": "Raymore",
        "state": "MO",
        "zip": "64083",
        "phone": "(816) 265-6134",
        "fax": "(816) 265-6136",
        "hours": {"mon_fri": "9AM-7PM", "sat": "9AM-5PM", "sun": "closed"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "288": {
        "name": "Price Chopper Pharmacy",
        "number": "288",
        "address": "9717 N. Ash Avenue",
        "city": "Kansas City",
        "state": "MO",
        "zip": "64157",
        "phone": "(816) 883-2775",
        "fax": "(816) 883-2778",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "319": {
        "name": "Price Chopper Pharmacy",
        "number": "319",
        "address": "15700 N US 169 Unit E",
        "city": "Smithville",
        "state": "MO",
        "zip": "64089",
        "phone": "(816) 532-6140",
        "fax": "(816) 532-6145",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "325": {
        "name": "Price Chopper Pharmacy",
        "number": "325",
        "address": "1191 NE McQuerry Road",
        "city": "Grain Valley",
        "state": "MO",
        "zip": "64029",
        "phone": "(816) 867-2496",
        "fax": "(816) 443-2973",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "359": {
        "name": "Price Chopper Pharmacy",
        "number": "359",
        "address": "109 North Cedar Street",
        "city": "Belton",
        "state": "MO",
        "zip": "64012",
        "phone": "(816) 265-6006",
        "fax": "(816) 265-6010",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "9AM-3PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "405": {
        "name": "Price Chopper Pharmacy",
        "number": "405",
        "address": "120 East 19th Street",
        "city": "Ottawa",
        "state": "KS",
        "zip": "66067",
        "phone": "(785) 242-4649",
        "fax": "(785) 242-2401",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "415": {
        "name": "Price Chopper Pharmacy",
        "number": "415",
        "address": "2600 Ensign Hill Drive",
        "city": "Platte City",
        "state": "MO",
        "zip": "64079",
        "phone": "(816) 431-2751",
        "fax": "(816) 431-2306",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "416": {
        "name": "Price Chopper Pharmacy",
        "number": "416",
        "address": "2219 N. Belt Highway",
        "city": "St. Joseph",
        "state": "MO",
        "zip": "64506",
        "phone": "(816) 596-8041",
        "fax": "(816) 596-8044",
        "hours": {"mon_fri": "9AM-8PM", "sat": "9AM-5PM", "sun": "10AM-4PM"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "425": {
        "name": "Cosentino's Market Pharmacy",
        "number": "425",
        "address": "8051 W 160th Street",
        "city": "Overland Park",
        "state": "KS",
        "zip": "66085",
        "phone": "(913) 647-3604",
        "fax": "(913) 239-0708",
        "hours": {"mon_fri": "9AM-7PM", "sat": "9AM-5PM", "sun": "closed"},
        "printer_ip": "",
        "printer_port": 9100,
    },
    "448": {
        "name": "Sun Fresh Pharmacy",
        "number": "448",
        "address": "4001 Mill Street",
        "city": "Kansas City",
        "state": "MO",
        "zip": "64111",
        "phone": "",
        "fax": "",
        "hours": {"mon_fri": "", "sat": "", "sun": ""},
        "printer_ip": "",
        "printer_port": 9100,
    },
}


def get_store_display_name(store_id: str) -> str:
    """Format store for patient-facing display: 'Name City (number)'"""
    store = STORES.get(store_id)
    if not store:
        return f"Unknown Store ({store_id})"
    # Use short brand name for display
    brand = store["name"].replace(" Pharmacy", "").replace(" Pharm", "")
    return f"{brand} {store['city']} ({store['number']})"


def get_store_list_for_form() -> list[dict]:
    """Return sorted list of stores for the web form dropdown."""
    result = []
    for store_id, store in STORES.items():
        result.append({
            "id": store_id,
            "label": get_store_display_name(store_id),
            "city": store["city"],
            "state": store["state"],
        })
    # Sort by state, then city, then store number
    result.sort(key=lambda s: (s["state"], s["city"], s["id"]))
    return result
